### ISSUE TITLE
Translate subcategory names and other main texts

### ISSUE THREAD

**Issue by per1234** [arduino/reference-hi#2]
There is some text to translate that is not in this repository's content. Please translate the following list and add the translation as a reply here:

- Arduino Reference
- The Arduino programming language Reference, organized into Functions, Variable and Constant, and Structure keywords.
- functions
- For controlling the Arduino board and performing computations.
- Digital I/O
- Analog I/O
- Zero, Due & MKR Family
- Advanced I/O
- Time
- Math
- Trigonometry
- Characters
- Random Numbers
- Bits and Bytes
- External Interrupts
- Interrupts
- Communication
- Serial
- USB
- variables
- Arduino data types and constants.
- Constants
- Conversion
- Data Types
- Variable Scope & Qualifiers
- Utilities
- structure
- The elements of Arduino (C++) code.
- Sketch
- Control Structure
- Further Syntax
- Arithmetic Operators
- Comparison Operators
- Boolean Operators
- Pointer Access Operators
- Bitwise Operators
- Compound Operators

**Comment by animeshsrivastava24** [comment]
> There is some text to translate that is not in this repository's content. Please translate the following list and add the translation as a reply here:
> 
> * Arduino Reference
- आर्डुइनो संदर्भ
> * The Arduino programming language Reference, organized into Functions, Variable and Constant, and Structure keywords.
- आर्डुइनो प्रोग्रामिंग भाषा संदर्भ, कार्य, परिवर्तनीय और निरंतर और संरचना कीवर्ड में व्यवस्थित है।
> * functions
- कार्यों
> * For controlling the Arduino board and performing computations.
- आर्डुइनो बोर्ड को नियंत्रित करने और गणना करने के लिए।
> * Digital I/O
- डिजिटल आई/ओ
> * Analog I/O
- एनालॉग आई/ओ
> * Zero, Due & MKR Family
- शून्य, देय और एमकेआर परिवार
> * Advanced I/O
- उन्नत आई/ओ
> * Time
- समय
> * Math
- गणित
> * Trigonometry
- त्रिकोणमिति
> * Characters
- वर्ण
> * Random Numbers
- रैंडम नंबर
> * Bits and Bytes
- बिट्स और बाइट्स
> * External Interrupts
- बाहरी रुकावट
> * Interrupts
- रुकावट
> * Communication
- संचार
> * Serial
- धारावाहिक
> * USB
- यु एस बी
> * variables
- चर
> * Arduino data types and constants.
- आर्डुइनो डेटा प्रकार और स्थिरांक।
> * Constants
- स्थिरांक
> * Conversion
- रूपांतरण
> * Data Types
- जानकारी का प्रकार
> * Variable Scope & Qualifiers
- चर स्कोप और क्वालिफायर
> * Utilities
- उपयोगिताएँ
> * structure
- संरचना
> * The elements of Arduino (C++) code.
- आर्डुइनो (C ++) कोड के तत्व।
> * Sketch
- स्केच
> * Control Structure
- नियंत्रण संरचना
> * Further Syntax
- आगे सिंटेक्स
> * Arithmetic Operators
- अंकगणितीय आपरेटर
> * Comparison Operators
- तुलना संचालक
> * Boolean Operators
- बूलियन ऑपरेटर्स
> * Pointer Access Operators
- पॉइंटर एक्सेस ऑपरेटर्स
> * Bitwise Operators
- बिटवाइज ऑपरेटर्स
> * Compound Operators
- यौगिक संचालक

@per1234 Please review and guide.
