### ISSUE TITLE
Translate site text

### ISSUE THREAD

**Issue by per1234** [arduino/reference-hi#3]
There is some text to translate that is not in this repository's content. Please translate the following list of words and add the translation as a reply here:

- Language Reference
- "Arduino programming language can be divided in three main parts: functions, values (variables and constants), and structure."
- Language
- functions
- variables
- structure
- Libraries
- Glossary
- Edit This Page
- `"The Arduino Reference text is licensed under a <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\" rel=\"noopener\">Creative Commons Attribution-Share Alike 3.0 License</a>."`
- `"Find anything that can be improved? <a href=\"https://github.com/arduino/reference-hi\" target=\"_blank\" rel=\"noopener\">Suggest corrections and new documentation via GitHub.</a>"`
- `"Doubts on how to use Github? Learn everything you need to know in <a href=\"https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37\" target=\"_blank\" rel=\"noopener\">this tutorial</a>."`

**Comment by animeshsrivastava24** [comment]
- भाषा संदर्भ
- "Arduino प्रोग्रामिंग भाषा को तीन मुख्य भागों में विभाजित किया जा सकता है: फ़ंक्शन, मान (चर और स्थिरांक), और संरचना।"
- भाषा
- कार्यों
- चर
- संरचना
- पुस्तकालय
- शब्दकोष
- इस पृष्ठ को संपादित करें
- `"Arduino संदर्भ पाठ <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\" rel=\"noopenerener"> क्रिएटिव कॉमन्स के तहत लाइसेंस प्राप्त है एट्रिब्यूशन-शेयर अलाइक 3.0 लाइसेंस </a>। "`
- `"जो कुछ भी सुधार किया जा सकता है उसे ढूंढें; <a href=\"https://github.com/arduino/reference-hi\" target=\"_blank\" rel=\"noopener\"> सुधार और नए दस्तावेज़ सुझाएं GitHub। </a>`
- `"Github का उपयोग करने के बारे में संदेह। <a href=\"https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37\" target=\"_blank\" rel=\"noopener\">इस ट्यूटोरियल</a> में वह सब कुछ जानें जो आपको जानना चाहिए।`

@per1234  Please review and guide.

**Comment by per1234** [comment]
Thanks so much @animeshsrivastava24! I have submitted these translations as well as those you made in https://github.com/arduino/reference-hi/issues/2 and the issues will be closed when that PR is merged.

**Comment by animeshsrivastava24** [comment]
@per1234 I have forked the repo and will keep on updating the work and then sync the content.
