### ISSUE TITLE
[ Use of Hindi Numbers] Confusion on the use of Hindi Numbers

### ISSUE THREAD

**Issue by animeshsrivastava24** [arduino/reference-hi#5]
@per1234 @smellai Most of the Hindi Language users does not use Hindi Numbers in their daily practice. The reason: Hindi Numbers are difficult to understand.
For example:
>A0 to A5 

will translate to

>A० से A५

If you ask my opinion, I am also not comfortable using them in my daily life practice. So, please guide me should I change the entire documentation to include the Hindi Numbers or not. 
I am confused because we are aiming for two goals with the documentation:
1) Translation to the Hindi Language (Following this point, Hindi Numbers must be included )
2) Easy understanding and use ( Following this point, they should be not).

**Comment by per1234** [comment]
First of all, I don't think `A0` and `A5` are a good example. These are variable names defined in the variant files (e.g, https://github.com/arduino/ArduinoCore-avr/blob/master/variants/standard/pins_arduino.h#L65-L72) and so will be the same in any language. You need to be careful to avoid translating this sort of thing. For the most part, any code should not be translated. Probably the only code you would want to translate is the comments in the examples. In some cases, it could make sense to translate the names of variables declared in the examples (as was done in the Portuguese translation), but you need to be sure the translated names are valid code and GCC does not support the Unicode characters of Hindi by default.

As for translating numbers when they are not part of code, for example:
https://github.com/arduino/reference-hi/blob/8f8a2d1ac29a64f5974169277eef16b21734254d/Language/Variables/Data%20Types/byte.adoc#L15
The sole intent of this project is to make Arduino more accessible to the users of the Hindi language. You should do whatever makes the documentation easiest for the target audience. You are free to make the decision of what that is.

**Comment by animeshsrivastava24** [comment]
@per1234  Thanks a lot for the feedback. Also, I'm sorry for quoting the wrong example, it should have been only numbers used in the description, not the code and the variables.
Sure, I'll do the translation to make it easier.
